<script lang="ts">
  let { oninspect }: { oninspect: (image: string) => void } = $props();

  interface Example {
    image: string;
    badges?: string[];
  }

  // Generated by: web/scripts/update-badges.sh
  // Run the script against a live backend to refresh these.
  const examples: Example[] = [
    { image: 'alpine:latest', badges: ['SBOM', 'ATT'] },
    { image: 'nginx:latest', badges: ['SBOM'] },
    { image: 'python:3.12-slim', badges: ['SBOM'] },
    { image: 'golang:1.21', badges: ['SBOM', 'ATT'] },
    { image: 'ghcr.io/hkolvenbach/oci-explorer:latest', badges: ['SBOM', 'VEX', 'ATT', 'SIG'] },
    { image: 'dmitriylewen/alpine:3.21.2', badges: ['VEX', 'ATT'] },
  ];

  // Match the colors used on the inspection page (ReferrersSection / constants.ts)
  const badgeColors: Record<string, string> = {
    SBOM: 'bg-cyan-500/20 text-cyan-300',
    VEX: 'bg-emerald-500/20 text-emerald-300',
    ATT: 'bg-violet-500/20 text-violet-300',
    SIG: 'bg-amber-500/20 text-amber-300',
  };
</script>

<div class="text-center py-16 dot-grid">
  <h2 class="text-3xl font-bold tracking-tight text-slate-100 mb-8">What's inside your container?</h2>
  <div class="flex flex-wrap justify-center gap-3">
    {#each examples as ex}
      <button
        onclick={() => oninspect(ex.image)}
        class="px-3.5 py-2.5 bg-slate-800 hover:bg-slate-750 border border-slate-600 hover:border-slate-500 rounded-md text-sm font-mono text-slate-200 flex items-center gap-2 btn-lift"
      >
        <span>{ex.image}</span>
        {#if ex.badges}
          <span class="flex gap-1">
            {#each ex.badges as b}
              <span class="px-1.5 py-0.5 text-[10px] rounded font-sans font-semibold {badgeColors[b]}">{b}</span>
            {/each}
          </span>
        {/if}
      </button>
    {/each}
  </div>
</div>
